import 'package:flutter/material.dart';

import 'model/MenuSections.dart';

class MenuModel {
  final String id;
  final String description;
  final String name;
  final Map<String, MenuSections> menu_sections;
  final Map<String, MenuItems> menu_items;
  final Map<String, MenuItemsOptions> menu_items_options;
  final Map<String, Availability> availability;
  final Map<String, dynamic> menu_modifiers;
  final List<String> menu_choice_sections;
  final List<String> menu_group_sections;

  MenuModel(
      {required this.id,
      required this.description,
      required this.name,
      required this.menu_sections,
      required this.menu_items,
      required this.menu_items_options,
      required this.availability,
      required this.menu_modifiers,
      required this.menu_choice_sections,
      required this.menu_group_sections});
}

class DB {
  static const data = {
    "status": "success",
    "data": {
      "id": "581e6cd3-3ea8-4d39-9cc6-238a82c32e7c",
      "description":
          "Desi Adda bietet eine große Auswahl an italienischer, chinesischer, deutscher, indischer, amerikanischer, thailändischer und internationaler Küche. Zu den Top-Angeboten von Desi Adda gehört Dum Biryani.",
      "name": "Restaurant Nidda",
      "menu_sections": {
        "1": {
          "id": 1,
          "name": "Hello World 1",
          "description":
              "Alle Pizzen werden mit Tomatensauce und Käse zubereitet.",
          "type": "CATEGORY",
          "menu_section_id": [],
          "menu_item_id": [42, 79, 80, 90, 93, 135],
          "availability_id": 28,
          "display_order": 9,
          "menu_item_option_id": [],
          "parent_item_id": [],
          "is_active": true,
          "is_disabled": false,
          "tax_percentage": 7,
          "menu_section_offers": [
            {"id": 84, "offer_id": 15, "menu_section_id": 1},
            {"id": 91, "offer_id": 16, "menu_section_id": 1}
          ]
        },
        "2": {
          "id": 2,
          "name": "Choice",
          "description": null,
          "type": "ADD_ON",
          "menu_section_id": [],
          "menu_item_id": [58, 59, 60, 61, 62],
          "parent_item_id": [],
          "menu_item_option_id": [],
          "availability_id": null,
          "display_order": 1,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "3": {
          "id": 3,
          "name": "Burger",
          "description": "",
          "type": "CATEGORY",
          "menu_section_id": [],
          "menu_item_id": [8, 9, 85],
          "availability_id": 29,
          "display_order": 3,
          "menu_item_option_id": [],
          "parent_item_id": [],
          "is_active": true,
          "is_disabled": false,
          "tax_percentage": 7,
          "menu_section_offers": [
            {"id": 85, "offer_id": 15, "menu_section_id": 3}
          ]
        },
        "4": {
          "id": 4,
          "name": "Drinks",
          "description": "",
          "type": "CATEGORY",
          "menu_section_id": [],
          "menu_item_id": [10, 11],
          "availability_id": 30,
          "display_order": 4,
          "menu_item_option_id": [],
          "parent_item_id": [],
          "is_active": true,
          "is_disabled": false,
          "tax_percentage": 19,
          "menu_section_offers": [
            {"id": 86, "offer_id": 15, "menu_section_id": 4}
          ]
        },
        "5": {
          "id": 5,
          "name": "Extra",
          "description": null,
          "type": "ADD_ON",
          "menu_section_id": [],
          "menu_item_id": [],
          "parent_item_id": [
            {"display_order": 1, "id": 12},
            {"display_order": 1, "id": 13},
            {"display_order": 1, "id": 14},
            {"display_order": 1, "id": 15},
            {"display_order": 1, "id": 16},
            {"display_order": 1, "id": 17},
            {"display_order": 1, "id": 18},
            {"display_order": 1, "id": 19}
          ],
          "menu_item_option_id": [],
          "availability_id": null,
          "display_order": 1,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "6": {
          "id": 6,
          "name": "Choice",
          "description": null,
          "type": "CHOICE",
          "menu_section_id": [],
          "menu_item_id": [],
          "parent_item_id": [],
          "menu_item_option_id": [1, 2, 3],
          "availability_id": null,
          "display_order": 1,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "7": {
          "id": 7,
          "name": "Extra",
          "description": null,
          "type": "ADD_ON",
          "menu_section_id": [],
          "menu_item_id": [],
          "parent_item_id": [
            {"display_order": 1, "id": 20},
            {"display_order": 1, "id": 21},
            {"display_order": 1, "id": 22},
            {"display_order": 1, "id": 23},
            {"display_order": 1, "id": 24},
            {"display_order": 1, "id": 25},
            {"display_order": 1, "id": 26}
          ],
          "menu_item_option_id": [],
          "availability_id": null,
          "display_order": 1,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "8": {
          "id": 8,
          "name": "Angebot",
          "description": "",
          "type": "CATEGORY",
          "menu_section_id": [],
          "menu_item_id": [27, 28, 29],
          "availability_id": 31,
          "display_order": 5,
          "menu_item_option_id": [],
          "parent_item_id": [],
          "is_active": true,
          "is_disabled": false,
          "tax_percentage": 7,
          "menu_section_offers": []
        },
        "10": {
          "id": 10,
          "name": "More 2 Pizza extra",
          "description": null,
          "type": "ADD_ON",
          "menu_section_id": [],
          "menu_item_id": [],
          "parent_item_id": [
            {"display_order": 1, "id": 36},
            {"display_order": 1, "id": 37},
            {"display_order": 1, "id": 38},
            {"display_order": 1, "id": 39},
            {"display_order": 1, "id": 40},
            {"display_order": 1, "id": 41}
          ],
          "menu_item_option_id": [],
          "availability_id": null,
          "display_order": 1,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "11": {
          "id": 11,
          "name": "Select Pizza 1",
          "description": null,
          "type": "GROUP",
          "menu_section_id": [],
          "menu_item_id": [],
          "parent_item_id": [
            {"display_order": 1, "id": 1},
            {"display_order": 1, "id": 5},
            {"display_order": 1, "id": 6},
            {"display_order": 1, "id": 7}
          ],
          "menu_item_option_id": [],
          "availability_id": null,
          "display_order": 1,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "12": {
          "id": 12,
          "name": "Select Pizza 2",
          "description": null,
          "type": "GROUP",
          "menu_section_id": [],
          "menu_item_id": [],
          "parent_item_id": [
            {"display_order": 1, "id": 1},
            {"display_order": 1, "id": 5},
            {"display_order": 1, "id": 6},
            {"display_order": 1, "id": 7}
          ],
          "menu_item_option_id": [],
          "availability_id": null,
          "display_order": 1,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "60": {
          "id": 60,
          "name": "Test Bundle",
          "description": "",
          "type": "CATEGORY",
          "menu_section_id": [],
          "menu_item_id": [1, 5, 8, 9, 10, 27],
          "availability_id": null,
          "display_order": 0,
          "menu_item_option_id": [],
          "parent_item_id": [],
          "is_active": true,
          "is_disabled": false,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "77": {
          "id": 77,
          "name": "Test Bundle 2",
          "description": null,
          "type": "GROUP",
          "menu_section_id": [],
          "menu_item_id": [8, 9, 85, 10, 11],
          "parent_item_id": [],
          "menu_item_option_id": [],
          "availability_id": null,
          "display_order": 0,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "78": {
          "id": 78,
          "name": "Test Bundle 3",
          "description": null,
          "type": "GROUP",
          "menu_section_id": [],
          "menu_item_id": [27, 28, 29, 1, 5, 8, 9, 10, 27],
          "parent_item_id": [],
          "menu_item_option_id": [],
          "availability_id": null,
          "display_order": 0,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "79": {
          "id": 79,
          "name": "Topping",
          "description": null,
          "type": "CHOICE",
          "menu_section_id": [],
          "menu_item_id": [],
          "parent_item_id": [],
          "menu_item_option_id": [126],
          "availability_id": null,
          "display_order": 0,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "81": {
          "id": 81,
          "name": "size",
          "description": null,
          "type": "CHOICE",
          "menu_section_id": [],
          "menu_item_id": [],
          "parent_item_id": [],
          "menu_item_option_id": [129, 130],
          "availability_id": null,
          "display_order": 0,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "82": {
          "id": 82,
          "name": "angebot starter",
          "description": null,
          "type": "GROUP",
          "menu_section_id": [],
          "menu_item_id": [],
          "parent_item_id": [
            {"display_order": 1, "id": 27},
            {"display_order": 1, "id": 28},
            {"display_order": 1, "id": 29}
          ],
          "menu_item_option_id": [],
          "availability_id": null,
          "display_order": 1,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "83": {
          "id": 83,
          "name": "drinks",
          "description": null,
          "type": "GROUP",
          "menu_section_id": [],
          "menu_item_id": [],
          "parent_item_id": [
            {"display_order": 1, "id": 10},
            {"display_order": 1, "id": 11}
          ],
          "menu_item_option_id": [],
          "availability_id": null,
          "display_order": 1,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "88": {
          "id": 88,
          "name": "Size 2",
          "description": null,
          "type": "GROUP",
          "menu_section_id": [],
          "menu_item_id": [],
          "parent_item_id": [
            {"display_order": 1, "id": 80},
            {"display_order": 1, "id": 42},
            {"display_order": 1, "id": 8},
            {"display_order": 1, "id": 9}
          ],
          "menu_item_option_id": [],
          "availability_id": null,
          "display_order": 1,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "89": {
          "id": 89,
          "name": "Size 2",
          "description": null,
          "type": "CHOICE",
          "menu_section_id": [],
          "menu_item_id": [],
          "parent_item_id": [],
          "menu_item_option_id": [135, 136, 137],
          "availability_id": null,
          "display_order": 0,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "90": {
          "id": 90,
          "name": "Menu Test BBM",
          "description": "Test Category created by BBM",
          "type": "CATEGORY",
          "menu_section_id": [],
          "menu_item_id": [94, 134],
          "availability_id": 42,
          "display_order": 10,
          "menu_item_option_id": [],
          "parent_item_id": [],
          "is_active": true,
          "is_disabled": false,
          "tax_percentage": 7,
          "menu_section_offers": []
        },
        "91": {
          "id": 91,
          "name": "Burger Test 1",
          "description": null,
          "type": "GROUP",
          "menu_section_id": [],
          "menu_item_id": [],
          "parent_item_id": [
            {"display_order": 1, "id": 8},
            {"display_order": 1, "id": 9},
            {"display_order": 1, "id": 85},
            {"display_order": 1, "id": 10},
            {"display_order": 1, "id": 79},
            {"display_order": 1, "id": 80}
          ],
          "menu_item_option_id": [],
          "availability_id": null,
          "display_order": 1,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "111": {
          "id": 111,
          "name": "Toppings Type 2",
          "description": null,
          "type": "ADD_ON",
          "menu_section_id": [],
          "menu_item_id": [],
          "parent_item_id": [
            {"display_order": 1, "id": 132},
            {"display_order": 1, "id": 133}
          ],
          "menu_item_option_id": [],
          "availability_id": null,
          "display_order": 1,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "112": {
          "id": 112,
          "name": "s",
          "description": null,
          "type": "CHOICE",
          "menu_section_id": [],
          "menu_item_id": [],
          "parent_item_id": [],
          "menu_item_option_id": [158, 159, 160],
          "availability_id": null,
          "display_order": 0,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        },
        "116": {
          "id": 116,
          "name": "size",
          "description": null,
          "type": "CHOICE",
          "menu_section_id": [],
          "menu_item_id": [],
          "parent_item_id": [],
          "menu_item_option_id": [173, 174, 175],
          "availability_id": null,
          "display_order": 0,
          "is_active": 1,
          "is_disabled": 0,
          "tax_percentage": 0,
          "menu_section_offers": []
        }
      },
      "menu_items": {
        "1": {
          "id": 1,
          "name": "modifier 1",
          "description": "test product",
          "price": 1,
          "price_currency": "EUR",
          "sku": "1",
          "is_available": 1,
          "parent_menu_section_id": [],
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": "",
          "suitable_diet": null,
          "image_url": null,
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        },
        "5": {
          "id": 5,
          "name": "Pizza Hawaii",
          "description": "",
          "price": 10,
          "price_currency": "EUR",
          "sku": "10",
          "is_available": 1,
          "parent_menu_section_id": [
            {"display_order": 1, "id": 6},
            {"display_order": 1, "id": 7}
          ],
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": "",
          "suitable_diet": null,
          "image_url": null,
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        },
        "6": {
          "id": 6,
          "name": "Pizza Peperoniwurst",
          "description": "mit Peperoniwurst",
          "price": 7.199999809265137,
          "price_currency": "EUR",
          "sku": "1",
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": "",
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1,
          "parent_menu_section_id": [
            {"display_order": 1, "id": 5}
          ]
        },
        "8": {
          "id": 8,
          "name": "Chicken Burger",
          "description": "",
          "price": 10,
          "price_currency": "EUR",
          "sku": "101",
          "is_available": 1,
          "parent_menu_section_id": [],
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": "",
          "suitable_diet": null,
          "image_url": null,
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        },
        "9": {
          "id": 9,
          "name": "Veg Burger",
          "description": "",
          "price": 8,
          "price_currency": "EUR",
          "sku": "102",
          "is_available": 1,
          "parent_menu_section_id": [],
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": "",
          "suitable_diet": null,
          "image_url": null,
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        },
        "10": {
          "id": 10,
          "name": "Cola",
          "description": "",
          "price": 3,
          "price_currency": "EUR",
          "sku": "201",
          "is_available": 1,
          "parent_menu_section_id": [],
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": "",
          "suitable_diet": null,
          "image_url": null,
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        },
        "11": {
          "id": 11,
          "name": "Fanta",
          "description": "",
          "price": 5,
          "price_currency": "EUR",
          "sku": "131",
          "is_available": 1,
          "parent_menu_section_id": [],
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": "",
          "suitable_diet": null,
          "image_url": null,
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        },
        "12": {
          "id": 12,
          "name": "mit Ananas",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "13": {
          "id": 13,
          "name": "mit Artischocken",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "14": {
          "id": 14,
          "name": "mit Bacon",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "15": {
          "id": 15,
          "name": "mit Barbecuesauce",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "16": {
          "id": 16,
          "name": "mit Basilikum",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "17": {
          "id": 17,
          "name": "mit Bohnen",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "18": {
          "id": 18,
          "name": "mit Bolognese",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "19": {
          "id": 19,
          "name": "mit Broccoli",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "20": {
          "id": 20,
          "name": " mit Ananas",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "21": {
          "id": 21,
          "name": "mit Artischocken",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "22": {
          "id": 22,
          "name": "mit Bacon",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "23": {
          "id": 23,
          "name": "mit Barbecuesauce",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "24": {
          "id": 24,
          "name": "mit Basilikum",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "25": {
          "id": 25,
          "name": "mit Bohnen",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "26": {
          "id": 26,
          "name": "mit Bolognese",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "27": {
          "id": 27,
          "name": "Mini Angebot",
          "description":
              "• 2 Mini Pizzen (Ø 21cm) nach Wahl • 1 kleiner gemischter Salat • Pizzabrötchen mit Aioli",
          "price": 21.989999771118164,
          "price_currency": "EUR",
          "sku": "1",
          "is_available": 1,
          "parent_menu_section_id": [
            {"display_order": 1, "id": 12},
            {"display_order": 1, "id": 10},
            {"display_order": 1, "id": 11}
          ],
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": "1",
          "suitable_diet": null,
          "image_url": null,
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        },
        "28": {
          "id": 28,
          "name": "Smart-Angebot",
          "description":
              "• 2 Medium Pizzen (Ø 30cm) nach Wahl • 1 großer gemischter Salat • Pizzabrötchen mit Aioli",
          "price": 13.869999885559082,
          "price_currency": "EUR",
          "sku": "1",
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": "1",
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1,
          "parent_menu_section_id": [
            {"display_order": 1, "id": 83},
            {"display_order": 1, "id": 82}
          ],
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        },
        "29": {
          "id": 29,
          "name": "Pasta Angebot",
          "description":
              "• 2 Pastagerichte nach Wahl • 1 kleiner gemischter Salat • Pizzabrötchen mit Aioli",
          "price": 32,
          "price_currency": "EUR",
          "sku": "1",
          "is_available": 1,
          "parent_menu_section_id": [],
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": "1",
          "suitable_diet": null,
          "image_url": null,
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        },
        "36": {
          "id": 36,
          "name": " mit Ananas",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "37": {
          "id": 37,
          "name": " mit Artischocken",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "38": {
          "id": 38,
          "name": "mit Bacon",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "39": {
          "id": 39,
          "name": " mit Barbecuesauce",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "40": {
          "id": 40,
          "name": "mit Basilikum",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "41": {
          "id": 41,
          "name": "mit Bohnen",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "42": {
          "id": 42,
          "name": "Test product",
          "description": "test",
          "price": 0,
          "price_currency": "EUR",
          "parent_menu_section_id": [
            {"display_order": 1, "id": 81},
            {"display_order": 0, "id": 79},
            {"display_order": 1, "id": 88},
            {"display_order": 1, "id": 111}
          ],
          "sku": "1",
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 1,
          "tags": "1",
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1,
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        },
        "79": {
          "id": 79,
          "name": "Cheesy Fries Spezial",
          "description": "Cheesy Fries Spezial",
          "price": 1,
          "price_currency": "EUR",
          "sku": "1",
          "is_available": 1,
          "parent_menu_section_id": [],
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": "1",
          "suitable_diet": null,
          "image_url": null,
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        },
        "80": {
          "id": 80,
          "name": "Cheesy Fries Rot-Weiß",
          "description": "Cheesy Fries Rot-Weiß",
          "price": 1,
          "price_currency": "EUR",
          "sku": "1",
          "is_available": 1,
          "parent_menu_section_id": [],
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": "1",
          "suitable_diet": null,
          "image_url": null,
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        },
        "85": {
          "id": 85,
          "name": "Lamm Burger",
          "description": "",
          "price": 10,
          "price_currency": "EUR",
          "sku": "10001",
          "is_available": 1,
          "parent_menu_section_id": [],
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": "",
          "suitable_diet": null,
          "image_url": null,
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        },
        "90": {
          "id": 90,
          "name": "test choice",
          "description": "choice multiple",
          "price": 20,
          "price_currency": "EUR",
          "sku": "1654",
          "is_available": 1,
          "parent_menu_section_id": [],
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": "54",
          "suitable_diet": null,
          "image_url": null,
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        },
        "93": {
          "id": 93,
          "name": "Test Size ",
          "description": "",
          "price": 0,
          "price_currency": "EUR",
          "parent_menu_section_id": [
            {"display_order": 1, "id": 89}
          ],
          "sku": "99",
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": "",
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1,
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        },
        "94": {
          "id": 94,
          "name": "Test Size",
          "description": "Size Test",
          "price": 0,
          "price_currency": "EUR",
          "sku": "99",
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": "",
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1,
          "parent_menu_section_id": [
            {"display_order": 1, "id": 91}
          ],
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        },
        "132": {
          "id": 132,
          "name": "chilli",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "133": {
          "id": 133,
          "name": "chilli",
          "description": null,
          "price": 1,
          "price_currency": "EUR",
          "sku": null,
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 0,
          "tags": null,
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1
        },
        "134": {
          "id": 134,
          "name": "test `",
          "description": "",
          "price": 12,
          "price_currency": "EUR",
          "parent_menu_section_id": [
            {"display_order": 1, "id": 112}
          ],
          "sku": "",
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 1,
          "tags": "",
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1,
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        },
        "135": {
          "id": 135,
          "name": "Pizza Margherita",
          "description": "",
          "price": 5,
          "price_currency": "EUR",
          "parent_menu_section_id": [
            {"display_order": 1, "id": 116}
          ],
          "sku": "145",
          "type": "MENU_ITEM",
          "display_order": 1,
          "is_new": 0,
          "is_non_veg": 0,
          "is_popular": 1,
          "tags": "",
          "suitable_diet": null,
          "image_url": null,
          "is_available": 1,
          "nutritions": [],
          "allergens": [],
          "additives": [],
          "deposit_info": []
        }
      },
      "menu_item_options": {
        "1": {
          "id": 1,
          "type": "SIZES",
          "value": "MINI",
          "name": "Mini, Ø 21cm",
          "price": 0
        },
        "2": {
          "id": 2,
          "type": "SIZES",
          "value": "MEDIUM",
          "name": "Medium, Ø 30cm",
          "price": 2
        },
        "3": {
          "id": 3,
          "type": "SIZES",
          "value": "LARGE",
          "name": "Large, Ø 40cm",
          "price": 4
        },
        "126": {
          "id": 126,
          "type": "OPTIONAL",
          "value": "OPTIONAL",
          "name": "test 1",
          "price": 2
        },
        "129": {
          "id": 129,
          "type": "OPTIONAL",
          "value": "OPTIONAL",
          "name": "small",
          "price": 10
        },
        "130": {
          "id": 130,
          "type": "OPTIONAL",
          "value": "OPTIONAL",
          "name": "medium",
          "price": 15
        },
        "135": {
          "id": 135,
          "type": "OPTIONAL",
          "value": "OPTIONAL",
          "name": "S",
          "price": 10
        },
        "136": {
          "id": 136,
          "type": "OPTIONAL",
          "value": "OPTIONAL",
          "name": "M",
          "price": 15
        },
        "137": {
          "id": 137,
          "type": "OPTIONAL",
          "value": "OPTIONAL",
          "name": "L",
          "price": 20
        },
        "158": {
          "id": 158,
          "type": "OPTIONAL",
          "value": "OPTIONAL",
          "name": "l",
          "price": 14
        },
        "159": {
          "id": 159,
          "type": "OPTIONAL",
          "value": "OPTIONAL",
          "name": "m",
          "price": 16
        },
        "160": {
          "id": 160,
          "type": "OPTIONAL",
          "value": "OPTIONAL",
          "name": "l",
          "price": 18
        },
        "173": {
          "id": 173,
          "type": "OPTIONAL",
          "value": "OPTIONAL",
          "name": "small",
          "price": 1
        },
        "174": {
          "id": 174,
          "type": "OPTIONAL",
          "value": "OPTIONAL",
          "name": "medium",
          "price": 2
        },
        "175": {
          "id": 175,
          "type": "OPTIONAL",
          "value": "OPTIONAL",
          "name": "Large",
          "price": 3
        }
      },
      "availability": {
        "10": {
          "id": 10,
          "starts": "08:00",
          "ends": "12:00",
          "days": "SUNDAY",
          "is_everyday": false,
          "is_all_time": true,
          "order_types": "PICKUP",
          "is_all_services": false
        },
        "11": {
          "id": 11,
          "starts": "08:00",
          "ends": "12:00",
          "days": "SUNDAY",
          "is_everyday": false,
          "is_all_time": true,
          "order_types": "PICKUP",
          "is_all_services": false
        },
        "12": {
          "id": 12,
          "starts": "08:00",
          "ends": "12:00",
          "days": "SUNDAY",
          "is_everyday": false,
          "is_all_time": true,
          "order_types": "PICKUP",
          "is_all_services": false
        },
        "28": {
          "id": 28,
          "starts": "00:00",
          "ends": "23:59",
          "days": "SUNDAY,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY",
          "is_everyday": true,
          "is_all_time": true,
          "order_types": "delivery,pickup,dine_in",
          "is_all_services": true
        },
        "29": {
          "id": 29,
          "starts": "00:00",
          "ends": "23:59",
          "days": "SUNDAY,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY",
          "is_everyday": true,
          "is_all_time": true,
          "order_types": "delivery,pickup,dine_in",
          "is_all_services": true
        },
        "30": {
          "id": 30,
          "starts": "00:00",
          "ends": "23:59",
          "days": "SUNDAY,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY",
          "is_everyday": true,
          "is_all_time": true,
          "order_types": "delivery,pickup,dine_in",
          "is_all_services": true
        },
        "31": {
          "id": 31,
          "starts": "00:00",
          "ends": "23:59",
          "days": "SUNDAY,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY",
          "is_everyday": true,
          "is_all_time": true,
          "order_types": "delivery,pickup,dine_in",
          "is_all_services": true
        },
        "42": {
          "id": 42,
          "starts": "00:00",
          "ends": "23:59",
          "days": "SUNDAY,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY",
          "is_everyday": true,
          "is_all_time": true,
          "order_types": "delivery,pickup,dine_in",
          "is_all_services": true
        }
      },
      "menu_modifiers": {},
      "menu_choice_sections": [],
      "menu_group_sections": []
    }
  };
}

class ConstColors {
  static Color? containerColor = Colors.grey[200];
  static Color? cardColor = Color(0xFFFCAAAC);
  static Color? radioButtonColor = Color(0xFF8A4C4F);
}
